### ISSUE TITLE
Notification when homey new firmware is available

### ISSUE THREAD

**Issue by spoelly** [matjaz/info.matjaz.candy#5]
Hi would like to have the option when een new firmware for homey is available the i can be notified on my phone. Is it possible to implement "new firmware" information in the candy app so that i can use it in a flow?

**Comment by irritanterik** [comment]
Does it need to be a flow trigger? That will require some kind of polling on the api/manager/updates/update content.

**Comment by matjaz** [comment]
yeah... using cron manager.. Homey events would be awesome, for this use case. :)

**Comment by spoelly** [comment]
I think it's the most flexible option because of the different notification methods.

**Comment by irritanterik** [comment]
If api/manager/updates/update returns [] there's no update.  
If there is an update it looks like:
`[{"changelog":{"en":"<ul style=\"text-align: left;color: rgb(97, 97, 97);background-color: rgb(255, 255, 255);\"><li>Added Flow conditions for sensor devices with a boolean capability<br/></li><li>Added support for 'Controlled' Z-Wave Command Classes</li><li>Added support for Z-Wave 'Variant Groups'<br/></li><li>Fixed a bug where some Z-Wave Command Classes wouldn't be parsed correctly<br/></li><li>Fixed a bug where the Z-Wave chip would become unresponsive after changing a region</li><li>Fixed a bug where Z-Wave default configuration values would not get applied<br/></li><li>Fixed a bug where updates could not be installed due to a 'extractpath_not_writable' error (this update may still show the error)</li><li>Fixed a bug where the geolocation would be`null`<br/></li><li>Reduced stuttering</li><li>Various minor improvements</li></ul>"},"date":"2016-10-12T18:22:29.750Z","version":"0.10.5","size":16748118}]`

**Comment by matjaz** [comment]
So sth. like trigger "Homey update available" with `version` token.

**Comment by irritanterik** [comment]
No need to use the cron manager, it has no advantages for short(ish) intervals. 
Checking on boot and every 10 minutes with setInterval will do.

**Comment by matjaz** [comment]
I assume /update  makes a request to Athom servers which I think they won't be happy if we all start pinging every 10 mins :)

**Comment by irritanterik** [comment]
@weejewel will polling /update/ actually trigger a request to Athom servers?

**Comment by matjaz** [comment]
btw... push/events would be a lot better option.

**Comment by spoelly** [comment]
i must agree that push/events is the best option.. but can it be done?

**Comment by WeeJeWel** [comment]
Firmware uses polling to reduce stress on our servers. There's currently no way to circumvent that :-)

**Comment by irritanterik** [comment]
Thanks for replying here @WeeJeWel .  Can you confirm that a request to api/manager/updates/update results in extra load on your servers? 
If so we can alternatively (gently) poll https://firmware.athom.com/api/update/changelog/?channel=beta/

**Comment by WeeJeWel** [comment]
Polling `/api/manager/updates/update` is okay, just don't do it too often please :-)

**Comment by matjaz** [comment]
resolved in #9
